/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createRootRoute } from '@tanstack/react-router'

import { Route as IndexRouteImport } from './routes/index'
import { Route as PPostNameRouteImport } from './routes/p/$postName'

const rootRouteImport = createRootRoute()

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PPostNameRoute = PPostNameRouteImport.update({
  id: '/p/$postName',
  path: '/p/$postName',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/p/$postName': typeof PPostNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/p/$postName': typeof PPostNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/p/$postName': typeof PPostNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/p/$postName'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/p/$postName'
  id: '__root__' | '/' | '/p/$postName'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PPostNameRoute: typeof PPostNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$postName': {
      id: '/p/$postName'
      path: '/p/$postName'
      fullPath: '/p/$postName'
      preLoaderRoute: typeof PPostNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PPostNameRoute: PPostNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
