name: "Run Tests"

permissions:
  contents: read
  statuses: write

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: "latest"

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build Turbo
        run: bun run build

      - name: Run tests
        run: bun run test-ci

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Deploy to Production
        run: |
          echo "Deploying application..."

      - name: notify vercel
        uses: vercel/repository-dispatch/actions/status@v1
        with:
          name: "Vercel - my-nook-web: test"
